"""make complaint_id in transaction model not nullable

Revision ID: 5ad92ad56067
Revises: bfef3dfd3bef
Create Date: 2023-03-28 19:33:46.224044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ad92ad56067'
down_revision = 'bfef3dfd3bef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'complaint_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'complaint_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
