"""empty message

Revision ID: f5d91dd3efa9
Revises: 1a26cfae6b0c
Create Date: 2023-03-19 18:00:21.473532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5d91dd3efa9'
down_revision = '1a26cfae6b0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('complaints', 'complainer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('complaints', 'complainer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
